[package]
name = "lang-jsonld"

authors = ["Arthur Vercruysse <arthur.vercruysse@outlook.com>"]
edition = "2021"
version = "0.1.0"

[dependencies]
async-trait.workspace  = true
bevy_ecs.workspace     = true
chumsky.workspace      = true
futures.workspace      = true
ropey.workspace        = true
serde_json.workspace   = true
sophia_api.workspace   = true
sophia_iri.workspace   = true
tracing.workspace      = true

lsp-core = { path = "../core/" }

[dev-dependencies]
test-log   = { version = "0.2.19", features = ["trace"] }
test-utils = { path = "../test-utils/" }
lang-turtle = { path = "../lang-turtle/" }
